### ISSUE TITLE
Gizmos Scheduler

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.Tasks#12]
In our project, we are using Svelto.ECS and split Client and Server into different project, both using Unity Engine, Client with UI/Sprite/Mesh, Server without UI/Sprite/Mesh. So for server development, we used gizmos for testing.

For example, we have `TroopEntity` and `TowerEntity`, both have detector for detecting enemy in certain radius. So we created : 

- `PositionGizmosEngine` for drawing position gizmos, which handle `PositionGizmosEntity` (extend EntityView)
- `EnemyDetectorGizmosEngine` for drawing detection radius gizmos, which handle `EnemyDetectorGizmosEntity` (extend EntityView). 

This is very useful for our development process.

I had asked you about gizmos before, but I am still thinking we need it. We need to drawing gizmos using ecs pattern, and our Svelto.ECS need this scheduler to draw gizmos.

This is what we made to handle gizmos. What do you think about integrate it in Svelto.Tasks?
[leopripos/Svelto.Tasks/tree/unity-gizmos-scheduler/Svelto.Tasks/Runners/Unity/Gizmos](https://github.com/leopripos/Svelto.Tasks/tree/unity-gizmos-scheduler/Svelto.Tasks/Runners/Unity/Gizmos)

*sorry about my english :)

**Comment by sebas77** [comment]
thanks for the suggestion. I am not sure if I see why this should be officially part of Svelto.Tasks. Svelto schedulers are actually designed to be extended, so you did good creating your own runner like this.

P.S.: I suggest to avoid using the LoopActionEnumerator. I am actually removing it from all the examples. The reason is that it hides the fact that Svelto.Tasks actually runs IEnumerator, plus it keeps you from being able to use nice tricks and especially using continuation (being able to yield task running on other runners)

**Comment by leopripos** [comment]
My opinion about "why it should be officially" because its relation with Svelto.ECS.
1. Most of unity development need gizmos as presentation data or behaviour.
2. Unity run gizmos depend on MonoBehaviour, but Svelto.ECS component and engine designed to not use MonoBehaviour (even though It can).

> P.S.: I suggest to avoid using the LoopActionEnumerator....

Noted
