### ISSUE TITLE
Shouldn't `IContinuationWrapper` inherit `IEnumerator`

### ISSUE THREAD

**Issue by PranavSK** [sebas77/Svelto.Tasks#18]
https://github.com/sebas77/Svelto.Tasks/blob/3fe0ccf44b2d212d266c39b5a208e699283c851a/Svelto.Tasks/SveltoTask.cs#L81

I believe the `IContinuationWrapper` should inherit `IEnumerator` so that we can use the `yield return` on these. Also `IsCompleted` from `ContinuationWrapper` must be a member of the `IContinuationWrapper` interface.

**Comment by sebas77** [comment]
the continuation wrapper is a little bastard. It's a singularity in my design which I much improved with Svelto.Tasks 2.0. You shouldn't hold a reference to it, so I am reducing it's functionality as much as I can. The reason why did this last minute modification, is because it should be always yielded by the framework only and not explicitly by you.
In Svelto.Tasks 2.0 I reintroduced the possibility for you to check if it's completed, only because in the new version is now a struct.
Do you have a code example for which this would result too limiting for you?

**Comment by PranavSK** [comment]
How would you start another task from the current one and wait for it?

**Comment by sebas77** [comment]
yield return task -> yields the current stack to the new task and executes it immediately. It actually replaces the calling task until the child task is done

yield return task.Run() -> generates a continuation enumerator and yields the current task until is done.

**Comment by PranavSK** [comment]
Ah yes the reason I put this issue was because of errors in the Task.Tests repo. Is the tests repo for the 2.0 version? 
And how usable is the 2.0 version right now?

**Comment by sebas77** [comment]
no, it should be all right, I may have forgot to do the final commit, checking now

**Comment by sebas77** [comment]
OK committed :)

**Comment by sebas77** [comment]
@PranavSK Svelto Tasks 2.0 is in pre alpha, I am starting to use it now, but on a new project company project so I can test it. Task Routines are not implemented yet.
